spring:
    activemq:
        broker-url: ${AMQ_BROKER_URL}
    datasource:
      platform: mariadb
      driverClassName: org.mariadb.jdbc.Driver
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      timeBetweenEvictionRunsMillis: 1000
      testWhileIdle: true
      liquibase:
        enabled: false
      hikari:
        connectionTimeout: 30000
        idleTimeout: 30000
        maxLifetime: 2000000
        maximumPoolSize: 20
        minimumIdle: 5
        poolName: SpringBootJPAHikariCP
      jpa:
        ddl-auto: ''
        show-sql: true
logging:
  level:
    com:
      scoperetail: DEBUG
fusion:
  sources:
      - name: walmart
        uri: ${URI_WALMART_SOURCE}
        bo: ${URI_WALMART_SOURCE_BO}
      - name: mfc
        uri: ${URI_MFC_SOURCE}
        bo: ${URI_MFC_SOURCE_BO}
  events:
    - eventType: ERROR_NOTIFICATION
      spec:
          source: walmart
          format: json
          eventTypePath: eventType
      headers:
        configLookupKey: configLookupKey/configLookupKey.ftl 
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate,direct:dedupe,direct:transform'
        actionExecution: sequence
      configSpec:
        default:
            validatorUri: 'json-validator:schema/ERROR_NOTIFICATION/error_notification.jsd'
            onValidationFailureUri: ${URI_WALMART_SOURCE_DEAD_LETTER}
            continueOnDuplicate: true
            transformationRequired: true
            transformerTemplateUri: 'templates/ERROR_NOTIFICATION/error_notification_message.ftl'
        ERROR_NOTIFICATION_2142_US:
            targetUri: ${URI_MFC_2142_US}
            
    - eventType: ERROR_NOTIFICATION
      spec:
          source: mfc
          format: json
          eventTypePath: eventType
      headers:
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
            validatorUri: 'json-validator:schema/ERROR_NOTIFICATION/error_notification.jsd'
            onValidationFailureUri: ${URI_MFC_SOURCE_DEAD_LETTER}
            transformationRequired: true
            transformerTemplateUri: 'templates/ERROR_NOTIFICATION/error_notification_message.ftl'
            targetUri: ${URI_WALMART_US}
                                           
    - eventType: ERROR_NOTIFICATION
      spec:
          source: walmart
          format: xml
          eventTypePath: eventType
      headers:
        configLookupKey: configLookupKey/configLookupKey.ftl 
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
            validatorUri: 'validator:schema/ERROR_NOTIFICATION/error_notification.xsd'
            onValidationFailureUri: ${URI_WALMART_SOURCE_DEAD_LETTER}
            transformationRequired: true
            transformerTemplateUri: 'templates/ERROR_NOTIFICATION/error_notification_message.ftl'
        ERROR_NOTIFICATION_2142_US:
            targetUri: ${URI_MFC_2142_US}

    - eventType: ORDER_DROP
      spec:
        source: walmart
        format: json
        eventTypePath: eventType
      headers:
        configLookupKey: configLookupKey/configLookupKey.ftl
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
          validatorUri: 'json-validator:schema/ORDER_DROP/order_drop.jsd'
          onValidationFailureUri: ${URI_WALMART_SOURCE_DEAD_LETTER}
          transformationRequired: true
          transformerTemplateUri: 'templates/ORDER_DROP/order_drop_message.ftl'
        ORDER_DROP_2142_US:
          targetUri: ${URI_MFC_2142_US}

    - eventType: PICK_BEGIN
      spec:
        source: mfc
        format: xml
        eventTypePath: eventType
      headers:
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
          validatorUri: 'validator:schema/PICK_BEGIN/pick_begin.xsd'
          onValidationFailureUri: ${URI_MFC_SOURCE_DEAD_LETTER}
          transformationRequired: true
          transformerTemplateUri: 'templates/PICK_BEGIN/pick_begin_message.ftl'
          targetUri: ${URI_WALMART_US}

    - eventType: PICK_COMPLETE
      spec:
        source: mfc
        format: xml
        eventTypePath: eventType
      headers:
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
          validatorUri: 'validator:schema/PICK_COMPLETE/pick_complete.xsd'
          onValidationFailureUri: ${URI_MFC_SOURCE_DEAD_LETTER}
          transformationRequired: true
          transformerTemplateUri: 'templates/PICK_COMPLETE/pick_complete_message.ftl'
          targetUri: ${URI_WALMART_US}

    - eventType: PICK_EVENT
      spec:
        source: mfc
        format: json
        eventTypePath: eventType
      headers:
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
          validatorUri: 'json-validator:schema/PICK_EVENT/pick_event.jsd'
          onValidationFailureUri: ${URI_MFC_SOURCE_DEAD_LETTER}
          transformationRequired: true
          transformerTemplateUri: 'templates/PICK_EVENT/pick_event_message.ftl'
          targetUri: ${URI_WALMART_US}

    - eventType: PICK_ORDER_CANCEL
      spec:
        source: walmart
        format: json
        eventTypePath: eventType
      headers:
        configLookupKey: configLookupKey/configLookupKey.ftl
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
          validatorUri: 'json-validator:schema/PICK_ORDER_CANCEL/pick_order_cancel.jsd'
          onValidationFailureUri: ${URI_WALMART_SOURCE_DEAD_LETTER}
          transformationRequired: true
          transformerTemplateUri: 'templates/PICK_ORDER_CANCEL/pick_order_cancel_message.ftl'
        PICK_ORDER_CANCEL_2142_US:
          targetUri: ${URI_MFC_2142_US}