fusion:
  sources:
      - name: kafka_order_drop
        type: kafka
        uri: kafka:test1?brokers=localhost:9092
        spec:
          format: json
          eventTypePath: $.eventType

  targets:
      - name: activemq_order_drop
        type: activemq
        uri: order_drop.${header.nodeId}.out
      - name: audit
        type: activemq
        uri: camel uri
  events:
      orderDrop:
        header:
          "nodeId"
          value: jsonPath
        - key: "countryCode"
          value: jsonPath
        - key: "configLookupKey"
          value: jsonPath
      spec:
        - key: "default"
          actions:
            validate:
              schema: jsd/xsd/schema - order_drop.jsd
              onFailureTarget: DLQ
            audit:
              enabled: true
              target: audit
            idempotence:
              enabled: true
              keyExpression: static/jsonPath/xpath
              continueOnDuplicate: false
            transform:
              template: order_drop.ftl
              target: activemq_order_drop
