spring:
    activemq:
        broker-url: tcp://127.0.0.1:61616
    datasource:
      platform: mariadb
      driverClassName: org.mariadb.jdbc.Driver
      url: jdbc:mariadb:failover://localhost:3306/fusion?autoReconnect=true
      username: root
      password: root
      timeBetweenEvictionRunsMillis: 1000
      testWhileIdle: true
      liquibase:
        enabled: false
      hikari:
        connectionTimeout: 30000
        idleTimeout: 30000
        maxLifetime: 2000000
        maximumPoolSize: 20
        minimumIdle: 5
        poolName: SpringBootJPAHikariCP
      jpa:
        ddl-auto: ''
        show-sql: true        
logging:
  level:
    com:
      scoperetail: DEBUG
kafka:
  bootStrapAddress: siren-kafka.eastus.cloudapp.azure.com:9092,siren-kafka.eastus.cloudapp.azure.com:9093,siren-kafka.eastus.cloudapp.azure.com:9094
fusion:
  sources:
      - name: walmart
        uri: 'kafka:walmart_source_topic?brokers=kafka-docker.eastus2.cloudapp.azure.com:9092&groupId=hawkeye-ing&securityProtocol=SASL_SSL&sslTruststoreLocation=/Users/javier/Projects/quikpik/jks/kafka.consumer.truststore.jks&sslTruststorePassword=confluent&sslEndpointAlgorithm=HTTPS&saslMechanism=SCRAM-SHA-256&saslJaasConfig=org.apache.kafka.common.security.scram.ScramLoginModule required username="kafkaclient" password="password";&autoCommitEnable=false&autoOffsetReset=earliest&maxPollIntervalMs=300000&maxPollRecords=1&requestTimeoutMs=60000&retryBackoffMs=60000&heartbeatIntervalMs=10000&sessionTimeoutMs=30000'
        bo: 'kafka:walmart_source_bo?brokers=kafka-docker.eastus2.cloudapp.azure.com:9092&groupId=hawk-eye-ing&securityProtocol=SASL_SSL&sslTruststoreLocation=/Users/javier/Projects/quikpik/jks/kafka.consumer.truststore.jks&sslTruststorePassword=confluent&sslEndpointAlgorithm=HTTPS&saslMechanism=SCRAM-SHA-256&saslJaasConfig=org.apache.kafka.common.security.scram.ScramLoginModule required username="kafkaclient" password="password";&autoCommitEnable=false&autoOffsetReset=earliest&maxPollIntervalMs=300000&maxPollRecords=1&requestTimeoutMs=60000&retryBackoffMs=60000&heartbeatIntervalMs=10000&sessionTimeoutMs=30000'
      - name: mfc
        uri: 'activemq:queue:mfc_source'
        bo: 'activemq:queue:mfc_source_bo'
  events:
    #--------------------------
    # ERROR NOTIFICATION
    #--------------------------
    - eventType: ERROR_NOTIFICATION
      spec:
          source: walmart
          format: json
          eventTypePath: eventType
      headers:
        configLookupKey: configLookupKey/configLookupKey.ftl 
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate,direct:dedupe,direct:transform'
        actionExecution: sequence
      configSpec:
        default:
            validatorUri: 'json-validator:schema/ERROR_NOTIFICATION/error_notification.jsd'
            onValidationFailureUri: 'activemq:queue:walmart_source_dead_letter'
            continueOnDuplicate: true
            transformationRequired: true
            transformerTemplateUri: 'templates/ERROR_NOTIFICATION/error_notification_message.ftl'
        ERROR_NOTIFICATION_2142_US:
            targetUri: 'activemq:queue:mfc_2142_US'
            
    - eventType: ERROR_NOTIFICATION
      spec:
          source: mfc
          format: json
          eventTypePath: eventType
      headers:
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
            validatorUri: 'json-validator:schema/ERROR_NOTIFICATION/error_notification.jsd'
            onValidationFailureUri: 'activemq:queue:mfc_source_dead_letter'
            transformationRequired: true
            transformerTemplateUri: 'templates/ERROR_NOTIFICATION/error_notification_message.ftl'
            targetUri: 'activemq:queue:walmart_US'
                                           
    - eventType: ERROR_NOTIFICATION
      spec:
          source: walmart
          format: xml
          eventTypePath: eventType
      headers:
        configLookupKey: configLookupKey/configLookupKey.ftl 
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
            validatorUri: 'validator:schema/ERROR_NOTIFICATION/error_notification.xsd'
            onValidationFailureUri: 'activemq:queue:walmart_source_dead_letter'
            transformationRequired: true
            transformerTemplateUri: 'templates/ERROR_NOTIFICATION/error_notification_message.ftl'
        ERROR_NOTIFICATION_2142_US:
            targetUri: 'activemq:queue:mfc_2142_US'

    #--------------------------
    # ORDER DROP
    #--------------------------
    - eventType: ORDER_DROP
      spec:
        source: walmart
        format: json
        eventTypePath: eventType
      headers:
        configLookupKey: configLookupKey/configLookupKey.ftl
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
          validatorUri: 'json-validator:schema/ORDER_DROP/order_drop.jsd'
          onValidationFailureUri: 'activemq:queue:walmart_source_dead_letter'
          transformationRequired: true
          transformerTemplateUri: 'templates/ORDER_DROP/order_drop_message.ftl'
        ORDER_DROP_2142_US:
          targetUri: 'activemq:queue:mfc_2142_US'

    #--------------------------
    # PICK BEGIN
    #--------------------------
    - eventType: PICK_BEGIN
      spec:
        source: mfc
        format: xml
        eventTypePath: eventType
      headers:
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
          validatorUri: 'validator:schema/PICK_BEGIN/pick_begin.xsd'
          onValidationFailureUri: 'activemq:queue:mfc_source_dead_letter'
          transformationRequired: true
          transformerTemplateUri: 'templates/PICK_BEGIN/pick_begin_message.ftl'
          targetUri: 'activemq:queue:walmart_US'

    #--------------------------
    # PICK COMPLETE
    #--------------------------
    - eventType: PICK_COMPLETE
      spec:
        source: mfc
        format: xml
        eventTypePath: eventType
      headers:
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
          validatorUri: 'validator:schema/PICK_COMPLETE/pick_complete.xsd'
          onValidationFailureUri: 'activemq:queue:mfc_source_dead_letter'
          transformationRequired: true
          transformerTemplateUri: 'templates/PICK_COMPLETE/pick_complete_message.ftl'
          targetUri: 'activemq:queue:walmart_US'

    #--------------------------
    # PICK EVENT
    #--------------------------
    - eventType: PICK_EVENT
      spec:
        source: mfc
        format: json
        eventTypePath: eventType
      headers:
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
          validatorUri: 'json-validator:schema/PICK_EVENT/pick_event.jsd'
          onValidationFailureUri: 'activemq:queue:mfc_source_dead_letter'
          transformationRequired: true
          transformerTemplateUri: 'templates/PICK_EVENT/pick_event_message.ftl'
          targetUri: 'activemq:queue:walmart_US'

    #--------------------------
    # ORDER CANCEL
    #--------------------------
    - eventType: PICK_ORDER_CANCEL
      spec:
        source: walmart
        format: json
        eventTypePath: eventType
      headers:
        configLookupKey: configLookupKey/configLookupKey.ftl
        idempotencyKey: idempotency/idempotency.ftl
        actions: 'direct:validate, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
          validatorUri: 'json-validator:schema/PICK_ORDER_CANCEL/pick_order_cancel.jsd'
          onValidationFailureUri: 'activemq:queue:walmart_source_dead_letter'
          transformationRequired: true
          transformerTemplateUri: 'templates/PICK_ORDER_CANCEL/pick_order_cancel_message.ftl'
        PICK_ORDER_CANCEL_2142_US:
          targetUri: 'activemq:queue:mfc_2142_US'