spring:
    activemq:
        broker-url: tcp://127.0.0.1:61616
logging:
  level:
    com:
      scoperetail: DEBUG
fusion:
  sources:
      - name: activemq_order_source
        uri: 'activemq:queue:order_source'
      - name: activemq_pick_event
        uri: 'activemq:queue:pick_event'        
  events:
    - eventType: orderDrop
      spec:
          source: activemq_order_source
          format: json
          eventTypePath: $.routingInfo.sourceNode.nodeId
      header:
        nodeId: $.routingInfo.destinationNode.nodeId
        countryCode: $.routingInfo.destinationNode.location.countryCode
        configLookupKey: configLookupKey.ftl  
        randomKey: camel ride
        idempotencyKey: idempotency.ftl
        actions: 'direct:validate, direct:audit, direct:dedupe, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
            validatorUri: 'json-validator:schema/order_drop.jsd'
            onValidationFailureUri: 'activemq:queue:dead_letter'
            auditEnabled: true
            auditTargetUri: 'activemq:queue:audit'
            idempotencyRequired: true
            continueOnDuplicate: true
            transformationRequired: true
            transformerTemplateUri: 'freemarker:templates/order_drop.ftl?contentCache=false'
            targetUri: 'activemq:queue:mcs_order_drop1,activemq:queue:mcs_order_drop2'
        orderDrop_2142_US:
            transformationRequired: true
            transformerTemplateUri: 'freemarker:orderDrop/templates/ftl/order_drop.ftl?contentCache=false'
            
    - eventType: pickBegin
      spec:
          source: activemq_pick_event
          format: xml
          eventTypePath: /pickingOrderBeginEventMessage
      header:
        nodeId: /pickingOrderBeginEventMessage/MessageBody/RoutingInfo/DestinationNode/nodeID/text()
        countryCode: /pickingOrderBeginEventMessage/MessageBody/RoutingInfo/DestinationNode/location/countryCode/text()
        configLookupKey: configLookupKey.ftl
        randomKey: camel ride
        idempotencyKey: expression
        actions: 'direct:validate, direct:audit, direct:dedupe, direct:transform'
        actionExecution: sequence
      configSpec:
        default:
#          actions:
            validatorUri: 'json-validator:schema/order_drop.jsd'
            onValidationFailureUri: 'kafka:dead_letter?brokers=localhost:9092'
            auditEnabled: true
            auditTargetUri: 'activemq:queue:audit'
            idempotencyRequired: true
            continueOnDuplicate: true
            transformationRequired: true
            transformerTemplateUri: 'freemarker:templates/order_drop.ftl?contentCache=false'
            targetUri: 'activemq:queue:mcs_order_drop1,activemq:queue:mcs_order_drop2'
        pickBegin_2142_US:
#          actions:
            transformationRequired: true
            transformerTemplateUri: 'freemarker:templates/order_drop.ftl?contentCache=false'            