fusion:
  sources:
      - name: kafka_topic
        type: kafka
        uri: kafka:test1?brokers=localhost:9092
        spec:
          format: json
          eventTypePath: $.eventType

  targets:
      - name: activemq_order_drop
        type: activemq
        uri: order_drop.${header.nodeId}.out
      - name: audit
        type: activemq
        uri: camel uri
  events:
    - eventType: orderDrop
      header:
        nodeId: $.nodeId
        countryCode: $.countryCode
#        configLookupKey: const('orderDrop').header('nodeId')
# configLookupKey - content based key
        configLookupKey: orderDrop_2142_US
        randomKey: camel ride
        idempotencyKey: expression
      spec:
        default:
          actions:
            validate:
              schema: order_drop.jsd
              onFailureTarget: DLQ
            audit:
              enabled: true
              target: audit
            idempotence:
              enabled: true
              continueOnDuplicate: false
            transform:
              template: order_drop.ftl
              target: activemq_order_drop

        orderDrop_2142_US:
          actions:
            transform:
              template: order_drop_xyz.ftl
              target: activemq_order_drop
    - eventType: pickBegin
    - eventType: pickEnd